`timescale 1ns/1ns

module ed1 ();
// generated by  HDL Direct 16.3-S021 (v16-3-85AK) 12/6/2010
// on Thu Jul 12 16:26:58 2012
// from ed1_lib/ED1/sch_1

  // global signal glbl.gnd_signal;
  // global signal glbl.vcc;

  wire  unnamed_1_csmt_i104_2;
  wire  unnamed_1_csmt_i106_2;
  wire  unnamed_1_csmt_i110_1;
  wire  unnamed_1_csmt_i117_2;
  wire  unnamed_1_csmt_i124_1;
  wire  unnamed_1_csmt_i133_2;
  wire  unnamed_1_csmt_i135_1;
  wire  unnamed_1_csmt_i140_1;
  wire  unnamed_1_csmt_i148_2;
  wire  unnamed_1_csmt_i153_2;
  wire  unnamed_1_csmt_i157_1;
  wire  unnamed_1_csmt_i170_1;
  wire  unnamed_1_csmt_i174_1;
  wire  unnamed_1_csmt_i185_2;
  wire  unnamed_1_csmt_i187_2;
  wire  unnamed_1_csmt_i189_2;
  wire  unnamed_1_csmt_i192_1;
  wire  unnamed_1_csmt_i200_2;
  wire  unnamed_1_csmt_i204_1;
  wire  unnamed_1_csmt_i211_2;
  wire  unnamed_1_csmt_i23_1;
  wire  unnamed_1_csmt_i24_2;
  wire  unnamed_1_csmt_i33_1;
  wire  unnamed_1_csmt_i42_2;
  wire  unnamed_1_csmt_i45_1;
  wire  unnamed_1_csmt_i54_2;
  wire  unnamed_1_csmt_i57_1;
  wire  unnamed_1_csmt_i66_2;
  wire  unnamed_1_csmt_i71_1;
  wire  unnamed_1_csmt_i80_2;
  wire  unnamed_1_csmt_i89_1;
  wire  unnamed_1_csmt_i93_1;
  wire  unnamed_1_dsmtsignal_i109_a;
  wire  unnamed_1_dsmtsignal_i123_a;
  wire  unnamed_1_dsmtsignal_i134_a;
  wire  unnamed_1_dsmtsignal_i139_a;
  wire  unnamed_1_dsmtsignal_i156_a;
  wire  unnamed_1_dsmtsignal_i169_a;
  wire  unnamed_1_dsmtsignal_i173_a;
  wire  unnamed_1_dsmtsignal_i193_a;
  wire  unnamed_1_dsmtsignal_i203_a;
  wire  unnamed_1_dsmtsignal_i25_a;
  wire  unnamed_1_dsmtsignal_i32_a;
  wire  unnamed_1_dsmtsignal_i44_a;
  wire  unnamed_1_dsmtsignal_i56_a;
  wire  unnamed_1_dsmtsignal_i70_a;
  wire  unnamed_1_dsmtsignal_i88_a;
  wire  unnamed_1_dsmtsignal_i92_a;
  wire  unnamed_1_dthsignal_i6_a;
  wire  unnamed_1_dthsignal_i6_c;
  wire  unnamed_1_dthsignal_i7_a;
  wire  unnamed_1_j5rt_i10_5;
  wire  unnamed_1_rsmt_i108_1;
  wire  unnamed_1_rsmt_i121_1;
  wire  unnamed_1_rsmt_i137_1;
  wire  unnamed_1_rsmt_i142_1;
  wire  unnamed_1_rsmt_i159_1;
  wire  unnamed_1_rsmt_i160_1;
  wire  unnamed_1_rsmt_i177_1;
  wire  unnamed_1_rsmt_i191_1;
  wire  unnamed_1_rsmt_i202_1;
  wire  unnamed_1_rsmt_i21_1;
  wire  unnamed_1_rsmt_i35_1;
  wire  unnamed_1_rsmt_i47_1;
  wire  unnamed_1_rsmt_i59_1;
  wire  unnamed_1_rsmt_i73_1;
  wire  unnamed_1_rsmt_i85_1;
  wire  unnamed_1_rsmt_i96_1;

  wire  gnd_signal;
  wire  page1_gnd_signal;
  wire  vcc;
  wire  page1_vcc;

  assign gnd_signal = glbl.gnd_signal;
  assign page1_gnd_signal = gnd_signal;
  assign vcc = glbl.vcc;
  assign page1_vcc = vcc;

  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign vcc  = glbl.vcc;
  assign vcc  = glbl.vcc;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign vcc  = glbl.vcc;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign vcc  = glbl.vcc;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;
  assign gnd_signal  = glbl.gnd_signal;

// begin instances 

  r_th_carbon page1_i1  (.\1 (unnamed_1_j5rt_i10_5),
	.\2 (/* unconnected */));

  r_th_carbon page1_i2  (.\1 (unnamed_1_j5rt_i10_5),
	.\2 (/* unconnected */));

  r_th_carbon page1_i3  (.\1 (unnamed_1_j5rt_i10_5),
	.\2 (/* unconnected */));

  r_th_carbon page1_i4  (.\1 (unnamed_1_j5rt_i10_5),
	.\2 (/* unconnected */));

  d_th_signal page1_i6  (.a(unnamed_1_dthsignal_i6_a),
	.c(unnamed_1_dthsignal_i6_c));

  d_th_signal page1_i7  (.a(unnamed_1_dthsignal_i7_a),
	.c(unnamed_1_dthsignal_i6_c));

  j_5_rt page1_i8  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (unnamed_1_j5rt_i10_5));

  j_5_rt page1_i9  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (unnamed_1_j5rt_i10_5));

  j_5_rt page1_i10  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (unnamed_1_j5rt_i10_5));

  j_5_rt page1_i11  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (unnamed_1_j5rt_i10_5));

  j_4_rt page1_i12  (.\1 (unnamed_1_dthsignal_i6_a),
	.\2 (unnamed_1_dthsignal_i7_a),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */));

  j_5_rt page1_i13  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (unnamed_1_j5rt_i10_5));

  j_5_rt page1_i14  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (unnamed_1_j5rt_i10_5));

  j_5_rt page1_i15  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (unnamed_1_j5rt_i10_5));

  j_5_rt page1_i16  (.\1 (/* unconnected */),
	.\2 (/* unconnected */),
	.\3 (/* unconnected */),
	.\4 (/* unconnected */),
	.\5 (unnamed_1_j5rt_i10_5));

  u_lm324_series page1_i17  (.\4 (glbl.vcc),
	.\11 (glbl.gnd_signal),
	.in(unnamed_1_rsmt_i21_1),
	.ip(unnamed_1_csmt_i24_2),
	.out(unnamed_1_dsmtsignal_i25_a));
  defparam page1_i17.size = 1;

  r_smt page1_i19  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i24_2));

  r_smt page1_i20  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i23_1));

  r_smt page1_i21  (.\1 (unnamed_1_rsmt_i21_1),
	.\2 (unnamed_1_csmt_i23_1));

  r_smt page1_i22  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i21_1));

  c_smt page1_i23  (.\1 (unnamed_1_csmt_i23_1),
	.\2 (glbl.gnd_signal));

  c_smt page1_i24  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i24_2));

  d_smt_signal page1_i25  (.a(unnamed_1_dsmtsignal_i25_a),
	.c(unnamed_1_csmt_i23_1));

  u_lm324_series page1_i28  (.in(unnamed_1_rsmt_i35_1),
	.ip(unnamed_1_csmt_i42_2),
	.out(unnamed_1_dsmtsignal_i32_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i28.size = 1;

  d_smt_schottky page1_i29  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i24_2));

  r_smt page1_i31  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i33_1));

  d_smt_signal page1_i32  (.a(unnamed_1_dsmtsignal_i32_a),
	.c(unnamed_1_csmt_i33_1));

  c_smt page1_i33  (.\1 (unnamed_1_csmt_i33_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i35  (.\1 (unnamed_1_rsmt_i35_1),
	.\2 (unnamed_1_csmt_i33_1));

  r_smt page1_i36  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i35_1));

  r_smt page1_i39  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i42_2));

  d_smt_schottky page1_i40  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i42_2));

  c_smt page1_i42  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i42_2));

  r_smt page1_i43  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i45_1));

  d_smt_signal page1_i44  (.a(unnamed_1_dsmtsignal_i44_a),
	.c(unnamed_1_csmt_i45_1));

  c_smt page1_i45  (.\1 (unnamed_1_csmt_i45_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i47  (.\1 (unnamed_1_rsmt_i47_1),
	.\2 (unnamed_1_csmt_i45_1));

  r_smt page1_i48  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i47_1));

  r_smt page1_i51  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i54_2));

  d_smt_schottky page1_i52  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i54_2));

  c_smt page1_i54  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i54_2));

  r_smt page1_i55  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i57_1));

  d_smt_signal page1_i56  (.a(unnamed_1_dsmtsignal_i56_a),
	.c(unnamed_1_csmt_i57_1));

  c_smt page1_i57  (.\1 (unnamed_1_csmt_i57_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i59  (.\1 (unnamed_1_rsmt_i59_1),
	.\2 (unnamed_1_csmt_i57_1));

  r_smt page1_i60  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i59_1));

  r_smt page1_i63  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i66_2));

  d_smt_schottky page1_i64  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i66_2));

  c_smt page1_i66  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i66_2));

  u_lm324_series page1_i67  (.in(unnamed_1_rsmt_i47_1),
	.ip(unnamed_1_csmt_i54_2),
	.out(unnamed_1_dsmtsignal_i44_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i67.size = 1;

  u_lm324_series page1_i68  (.in(unnamed_1_rsmt_i59_1),
	.ip(unnamed_1_csmt_i66_2),
	.out(unnamed_1_dsmtsignal_i56_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i68.size = 1;

  r_smt page1_i69  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i71_1));

  d_smt_signal page1_i70  (.a(unnamed_1_dsmtsignal_i70_a),
	.c(unnamed_1_csmt_i71_1));

  c_smt page1_i71  (.\1 (unnamed_1_csmt_i71_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i73  (.\1 (unnamed_1_rsmt_i73_1),
	.\2 (unnamed_1_csmt_i71_1));

  r_smt page1_i74  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i73_1));

  u_lm324_series page1_i76  (.\4 (glbl.vcc),
	.\11 (glbl.gnd_signal),
	.in(unnamed_1_rsmt_i73_1),
	.ip(unnamed_1_csmt_i80_2),
	.out(unnamed_1_dsmtsignal_i70_a));
  defparam page1_i76.size = 1;

  r_smt page1_i77  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i80_2));

  d_smt_schottky page1_i78  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i80_2));

  c_smt page1_i80  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i80_2));

  c_smt page1_i82  (.\1 (glbl.gnd_signal),
	.\2 (glbl.vcc));

  c_smt page1_i83  (.\1 (glbl.gnd_signal),
	.\2 (glbl.vcc));

  r_smt page1_i85  (.\1 (unnamed_1_rsmt_i85_1),
	.\2 (unnamed_1_csmt_i89_1));

  r_smt page1_i86  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i85_1));

  r_smt page1_i87  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i89_1));

  d_smt_signal page1_i88  (.a(unnamed_1_dsmtsignal_i88_a),
	.c(unnamed_1_csmt_i89_1));

  c_smt page1_i89  (.\1 (unnamed_1_csmt_i89_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i91  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i93_1));

  d_smt_signal page1_i92  (.a(unnamed_1_dsmtsignal_i92_a),
	.c(unnamed_1_csmt_i93_1));

  c_smt page1_i93  (.\1 (unnamed_1_csmt_i93_1),
	.\2 (glbl.gnd_signal));

  u_lm324_series page1_i95  (.in(unnamed_1_rsmt_i85_1),
	.ip(unnamed_1_csmt_i104_2),
	.out(unnamed_1_dsmtsignal_i88_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i95.size = 1;

  r_smt page1_i96  (.\1 (unnamed_1_rsmt_i96_1),
	.\2 (unnamed_1_csmt_i93_1));

  r_smt page1_i97  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i104_2));

  d_smt_schottky page1_i98  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i104_2));

  r_smt page1_i99  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i96_1));

  u_lm324_series page1_i100  (.in(unnamed_1_rsmt_i96_1),
	.ip(unnamed_1_csmt_i106_2),
	.out(unnamed_1_dsmtsignal_i92_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i100.size = 1;

  r_smt page1_i101  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i106_2));

  d_smt_schottky page1_i102  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i106_2));

  c_smt page1_i104  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i104_2));

  c_smt page1_i106  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i106_2));

  r_smt page1_i107  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i110_1));

  r_smt page1_i108  (.\1 (unnamed_1_rsmt_i108_1),
	.\2 (unnamed_1_csmt_i110_1));

  d_smt_signal page1_i109  (.a(unnamed_1_dsmtsignal_i109_a),
	.c(unnamed_1_csmt_i110_1));

  c_smt page1_i110  (.\1 (unnamed_1_csmt_i110_1),
	.\2 (glbl.gnd_signal));

  u_lm324_series page1_i112  (.in(unnamed_1_rsmt_i108_1),
	.ip(unnamed_1_csmt_i117_2),
	.out(unnamed_1_dsmtsignal_i109_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i112.size = 1;

  r_smt page1_i113  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i108_1));

  r_smt page1_i114  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i117_2));

  d_smt_schottky page1_i115  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i117_2));

  c_smt page1_i117  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i117_2));

  r_smt page1_i118  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i124_1));

  r_smt page1_i119  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i135_1));

  r_smt page1_i120  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i140_1));

  r_smt page1_i121  (.\1 (unnamed_1_rsmt_i121_1),
	.\2 (unnamed_1_csmt_i124_1));

  c_smt page1_i122  (.\1 (glbl.gnd_signal),
	.\2 (glbl.vcc));

  d_smt_signal page1_i123  (.a(unnamed_1_dsmtsignal_i123_a),
	.c(unnamed_1_csmt_i124_1));

  c_smt page1_i124  (.\1 (unnamed_1_csmt_i124_1),
	.\2 (glbl.gnd_signal));

  u_lm324_series page1_i127  (.\4 (glbl.vcc),
	.\11 (glbl.gnd_signal),
	.in(unnamed_1_rsmt_i121_1),
	.ip(unnamed_1_csmt_i133_2),
	.out(unnamed_1_dsmtsignal_i123_a));
  defparam page1_i127.size = 1;

  r_smt page1_i129  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i121_1));

  r_smt page1_i131  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i133_2));

  d_smt_schottky page1_i132  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i133_2));

  c_smt page1_i133  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i133_2));

  d_smt_signal page1_i134  (.a(unnamed_1_dsmtsignal_i134_a),
	.c(unnamed_1_csmt_i135_1));

  c_smt page1_i135  (.\1 (unnamed_1_csmt_i135_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i137  (.\1 (unnamed_1_rsmt_i137_1),
	.\2 (unnamed_1_csmt_i135_1));

  u_lm324_series page1_i138  (.in(unnamed_1_rsmt_i137_1),
	.ip(unnamed_1_csmt_i148_2),
	.out(unnamed_1_dsmtsignal_i134_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i138.size = 1;

  d_smt_signal page1_i139  (.a(unnamed_1_dsmtsignal_i139_a),
	.c(unnamed_1_csmt_i140_1));

  c_smt page1_i140  (.\1 (unnamed_1_csmt_i140_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i142  (.\1 (unnamed_1_rsmt_i142_1),
	.\2 (unnamed_1_csmt_i140_1));

  u_lm324_series page1_i143  (.in(unnamed_1_rsmt_i142_1),
	.ip(unnamed_1_csmt_i153_2),
	.out(unnamed_1_dsmtsignal_i139_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i143.size = 1;

  r_smt page1_i144  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i137_1));

  r_smt page1_i145  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i148_2));

  d_smt_schottky page1_i146  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i148_2));

  c_smt page1_i148  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i148_2));

  r_smt page1_i149  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i142_1));

  r_smt page1_i150  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i153_2));

  d_smt_schottky page1_i151  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i153_2));

  c_smt page1_i153  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i153_2));

  r_smt page1_i154  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i157_1));

  c_smt page1_i155  (.\1 (glbl.gnd_signal),
	.\2 (glbl.vcc));

  d_smt_signal page1_i156  (.a(unnamed_1_dsmtsignal_i156_a),
	.c(unnamed_1_csmt_i157_1));

  c_smt page1_i157  (.\1 (unnamed_1_csmt_i157_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i159  (.\1 (unnamed_1_rsmt_i159_1),
	.\2 (unnamed_1_csmt_i170_1));

  r_smt page1_i160  (.\1 (unnamed_1_rsmt_i160_1),
	.\2 (unnamed_1_csmt_i157_1));

  r_smt page1_i161  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i160_1));

  u_lm324_series page1_i163  (.\4 (glbl.vcc),
	.\11 (glbl.gnd_signal),
	.in(unnamed_1_rsmt_i160_1),
	.ip(unnamed_1_csmt_i185_2),
	.out(unnamed_1_dsmtsignal_i156_a));
  defparam page1_i163.size = 1;

  r_smt page1_i165  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i185_2));

  r_smt page1_i166  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i159_1));

  d_smt_schottky page1_i167  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i185_2));

  r_smt page1_i168  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i170_1));

  d_smt_signal page1_i169  (.a(unnamed_1_dsmtsignal_i169_a),
	.c(unnamed_1_csmt_i170_1));

  c_smt page1_i170  (.\1 (unnamed_1_csmt_i170_1),
	.\2 (glbl.gnd_signal));

  r_smt page1_i172  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i174_1));

  d_smt_signal page1_i173  (.a(unnamed_1_dsmtsignal_i173_a),
	.c(unnamed_1_csmt_i174_1));

  c_smt page1_i174  (.\1 (unnamed_1_csmt_i174_1),
	.\2 (glbl.gnd_signal));

  u_lm324_series page1_i176  (.in(unnamed_1_rsmt_i159_1),
	.ip(unnamed_1_csmt_i187_2),
	.out(unnamed_1_dsmtsignal_i169_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i176.size = 1;

  r_smt page1_i177  (.\1 (unnamed_1_rsmt_i177_1),
	.\2 (unnamed_1_csmt_i174_1));

  r_smt page1_i178  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i187_2));

  d_smt_schottky page1_i179  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i187_2));

  r_smt page1_i180  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i177_1));

  u_lm324_series page1_i181  (.in(unnamed_1_rsmt_i177_1),
	.ip(unnamed_1_csmt_i189_2),
	.out(unnamed_1_dsmtsignal_i173_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i181.size = 1;

  r_smt page1_i182  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i189_2));

  d_smt_schottky page1_i183  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i189_2));

  c_smt page1_i185  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i185_2));

  c_smt page1_i187  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i187_2));

  c_smt page1_i189  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i189_2));

  r_smt page1_i190  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i192_1));

  r_smt page1_i191  (.\1 (unnamed_1_rsmt_i191_1),
	.\2 (unnamed_1_csmt_i192_1));

  c_smt page1_i192  (.\1 (unnamed_1_csmt_i192_1),
	.\2 (glbl.gnd_signal));

  d_smt_signal page1_i193  (.a(unnamed_1_dsmtsignal_i193_a),
	.c(unnamed_1_csmt_i192_1));

  u_lm324_series page1_i194  (.in(unnamed_1_rsmt_i191_1),
	.ip(unnamed_1_csmt_i200_2),
	.out(unnamed_1_dsmtsignal_i193_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i194.size = 1;

  r_smt page1_i196  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i191_1));

  r_smt page1_i197  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i200_2));

  d_smt_schottky page1_i198  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i200_2));

  c_smt page1_i200  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i200_2));

  r_smt page1_i201  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i204_1));

  r_smt page1_i202  (.\1 (unnamed_1_rsmt_i202_1),
	.\2 (unnamed_1_csmt_i204_1));

  d_smt_signal page1_i203  (.a(unnamed_1_dsmtsignal_i203_a),
	.c(unnamed_1_csmt_i204_1));

  c_smt page1_i204  (.\1 (unnamed_1_csmt_i204_1),
	.\2 (glbl.gnd_signal));

  u_lm324_series page1_i206  (.in(unnamed_1_rsmt_i202_1),
	.ip(unnamed_1_csmt_i211_2),
	.out(unnamed_1_dsmtsignal_i203_a),
	.\4 (/* unconnected */),
	.\11 (/* unconnected */));
  defparam page1_i206.size = 1;

  r_smt page1_i207  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_rsmt_i202_1));

  r_smt page1_i208  (.\1 (glbl.gnd_signal),
	.\2 (unnamed_1_csmt_i211_2));

  d_smt_schottky page1_i209  (.a(glbl.gnd_signal),
	.c(unnamed_1_csmt_i211_2));

  c_smt page1_i211  (.\1 (/* unconnected */),
	.\2 (unnamed_1_csmt_i211_2));

endmodule // ed1(sch_1) 
